version: "3.9"

services:
  xagent:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: artifex
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      SPRING_PROFILES_ACTIVE: test